### ISSUE TITLE
Help us improve the README.md file by adding project screenshots

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#1]
<img width="1134" alt="o1" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/bb31813e-ed50-4768-ad11-680c6f4f6543">
<img width="1061" alt="o2" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/e8f2b9af-3aea-486f-908c-5e2e254e9872">
<img width="1056" alt="o3" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/925873bd-7f9f-46a7-8531-63d896a6b385">
We are super excited for our launch on ProductHunt tomorrow(19th Oct). We would like somebody to help us improve the readme file by adding screenshots from attachments to it and format it correctly. The images should be aligned correctly and open in full size on clicking.

**Comment by dakshsinghrathore** [comment]
Hey @nxglabs I would love to contribute ! Kindly assign this issue to me. 
Do share the attachments whose SS I need to attach .

**Comment by nxglabs** [comment]
Updated the issue with attachments. Thanks.

**Comment by nxglabs** [comment]
@dakshsinghrathore Are you still interested in getting this done?
