### ISSUE TITLE
Design is not mobile friendly

### ISSUE THREAD

**Issue by rasel9t6** [OpenSignLabs/OpenSign#106]
- Clickable navbar elements are cropped when screen size bellow 970px.

- Content does not appear properly in small screen.
- Footer copyright information not align perfectly in small screen.

![Screenshot 2023-10-31 202952](https://github.com/OpenSignLabs/OpenSign/assets/116421413/a7f9f736-a40a-4ef5-9ec6-7660db5736b1)

**Comment by kundan766** [comment]
can you assign me the issue

**Comment by nxglabs** [comment]
Website is not a part of this repo. Anyways, you need to refresh it to load it in mobile view.
