### ISSUE TITLE
docs, early days - thoughts?

### ISSUE THREAD

**Issue by scafati98** [OpenSignLabs/OpenSign#111]
building some docs for devs of this library, still early days so feedback is welcome to enhance it.
WDYT?

[docs](https://demo.autonoma.app/docs/2dbdc188-ee09-4f4a-a2f8-ce28771df5be/8a903120-6ef6-4ebf-8e29-4788ac423b8b)

**Comment by andrew-opensignlabs** [comment]
Great. Thanks @scafati98 
We will definitely re-use some content from it in our docs which is WIP.
