### ISSUE TITLE
[Bug]: Does not have initial create admin account part after install from scratch

### ISSUE THREAD

**Issue by MaiXuanHoang** [OpenSignLabs/OpenSign#1115]
### Issue Description

Hello,

After install Opensign from scratch follow with this docs: https://docs.opensignlabs.com/docs/self-host/docker/run-locally/
I cannot login to Opensign cause the create account admin part doesn't have for my local, access to localhost:3000 OK,
My OS is Ubuntu 22.04

### Expected Behavior

I must have the part to create admin account in the first step

### Steps to reproduce

Run Opensign locally: curl --remote-name-all https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/docker-compose.yml https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/Caddyfile https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/.env.local_dev && mv .env.local_dev .env.prod && docker compose up --force-recreate
and access to localhost:3000 after that, does not have interface to create admin account

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Ubuntu 22.04

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

Latest

### What environment are you seeing the problem on?

Dev (localhost or vercel)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
You need to access it from localhost:3001 and not localhost:3000

**Comment by MaiXuanHoang** [comment]
Sorry for late response but only localhost:3000 works

**Comment by MaiXuanHoang** [comment]
`root@opensign:~# curl localhost:3000
<!doctype html><html lang="en" data-theme="opensigncss"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="The fastest way to sign PDFs & request signatures from others"/><link rel="manifest" href="/manifest.json"/><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/><link rel="stylesheet" href="https://cdn.opensignlabs.com/fonts.css"/><title>OpenSign™</title><script defer="defer" src="/static/js/main.3aafcbc6.js"></script><link href="/static/css/main.86cc883d.css" rel="stylesheet"></head><body><div id="root"></div></body></html>root@opensign:~#
root@opensign:~# curl localhost:3001
Client sent an HTTP request to an HTTPS server.`

**Comment by MaiXuanHoang** [comment]
It works today, thanks,

**Comment by adi6409** [comment]
How did you fix this?

**Comment by MaiXuanHoang** [comment]
I just change the port 3001 to 3000, but the credential was setup with port 3001 cannot use on 3000, only works for https://localhost:3001,
Tried changes a lot of things in .env and docker-compose file but the app just working with port 3001 :(
