### ISSUE TITLE
Select Folder modal is not user friendly

### ISSUE THREAD

**Issue by yadavrashindra5** [OpenSignLabs/OpenSign#112]
**Issue**
When clicking on the pencil icon within 'Sign Yourself,' it opens a modal for creating a folder. However, when the sidebar and the modal for creating a folder are open, the button on the modal gets hidden behind the sidebar, affecting user visibility.

![image](https://github.com/OpenSignLabs/OpenSign/assets/54495038/2f92b947-466f-488a-96d0-9587d532b6b6)

![image](https://github.com/OpenSignLabs/OpenSign/assets/54495038/4da5007f-045d-41ef-b701-95c3d87ea533)
![image](https://github.com/OpenSignLabs/OpenSign/assets/54495038/1059ec3e-02d0-403b-b9e4-e5c48d7c7d37)

**Comment by yadavrashindra5** [comment]
@nxglabs assign this to me I am willing to work on this issue.

**Comment by yadavrashindra5** [comment]
@nxglabs is permission required to raise PR?

**Comment by nxglabs** [comment]
No. Permission/review is required to merge it. Do share the screenshot here once you have done the changes.

**Comment by andrew-opensignlabs** [comment]
resolved in pull request #118
