### ISSUE TITLE
[Bug]: When signing from dashboard, OTP is requested but never sent

### ISSUE THREAD

**Issue by evanash16** [OpenSignLabs/OpenSign#1134]
### Issue Description

I am the owner of a document that I've requested signatures on, and am the first person to sign. I confirmed that no one else has received the document, so I assumed I needed to sign it to unblock them.

When I went to sign the document from my dashboard (which was the only option since an email wasn't sent with a link), it requested that I enter a one-time password sent to my email. This was never sent, so I wasn't able to verify with a one-time password, and was not able to sign the document.

### Expected Behavior

When I click "Send" on the "enter OTP" modal, I would expect a one-time password is sent to my email, even though I'm logged in.

### Current Behavior

When I click "Send" on the "enter OTP" modal, a one-time password is not sent. When I click "Resend", a one-time password is not sent.

### Steps to reproduce

1. Create a document template with yourself as a signer.
2. Send the document to yourself.
3. Sign the document via your dashboard.
4. Request a one-time password.

### Screenshots of the issue(optional)

<img width="511" alt="Screenshot 2024-08-29 at 1 08 00 PM" src="https://github.com/user-attachments/assets/64254e30-489d-4807-98eb-6f2fd2f848d1">

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

MacOS Ventura 13.1

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

N/A, on hosted website

### What environment are you seeing the problem on?

Production (app.opensignlabs.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
Looks like the email was not delivered to your email due to some reason. Please send an email to help@opensignlabs.com from your registered email id so that we can check the email delivery logs and get back to you.

I am assuming that you have checked your spam folder.

**Comment by andrew-opensignlabs** [comment]
@evanash16 I could see that an email was successfully delivered to your email address before approximately 5 hrs. Please check your spam folder again and mark it not spam.

**Comment by evanash16** [comment]
Interesting! I couldn't see any emails in my spam folder, and I do know that it works with my email domain as other people on the document had the same address. Perhaps there's a setting on my email that I'm missing.

Thanks anyway for the help!

**Comment by evanash16** [comment]
Just a quick update, there were some mail filters configured on my email account which automatically discarded messages before they went to my inbox. I would guess that the email address sending the OTP matched these mail filters as after removing them and requesting an OTP, my inbox received the OTP. Thanks again!

**Comment by MaiXuanHoang** [comment]
Hello @andrew-opensignlabs,
I have got the situation related to sending OTPs code, I am using SMTP google server (smtp.google.com) and here is my configure in .env.prod file:
"
MAILGUN_API_KEY=
MAILGUN_DOMAIN=mail.yourdomain.com
MAILGUN_SENDER=postmaster@mail.yourdomain.com
SMTP_ENABLE=true
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USER_EMAIL=myemail@gmail.com
SMTP_PASS=mypassword
"

I'm sure that 3 ports 25,465,587 are open, but the OTPs code just sent to docker logs, not end-user mailbox as I expected,

Docker logs:
"
err in sendmailv3 Error: Connection timeout
    at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)
    at SMTPConnection._onError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:20)
    at Timeout.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:237:22)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
OTP sent 7937
"
