### ISSUE TITLE
[Bug]: Signature errors

### ISSUE THREAD

**Issue by EDIflyer** [OpenSignLabs/OpenSign#1181]
### Issue Description

Loading the signed PDF in Adobe Acrobat shows signature errors

### Expected Behavior

No signature errors

### Current Behavior

Showing errors (see screenshots)

### Steps to reproduce

1. Sign document with OpenSign
2. View signed document in Adobe Acrobat

### Screenshots of the issue(optional)

![image](https://github.com/user-attachments/assets/e22073be-e815-4ab6-a95c-66e7f04851cb)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Any

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.2.0

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
Can you share the signed document on hello@opensignlabs.com so that we can investigate this further?

**Comment by EDIflyer** [comment]
Hi @andrew-opensignlabs - no probs, have emailed it to you just now.

**Comment by andrew-opensignlabs** [comment]
It seems the document hasn't been signed on our hosted version. Just tried signing it and it works perfectly.
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/0ade738a-da7c-41d7-ad8e-d3efb51ecfa0">
If you're using the self-hosted version, you'll need to purchase a document signing certificate and configure it in the environment variables.

**Comment by EDIflyer** [comment]
Yes, it's the self-hosted version I'm using - sorry for not making that clear, I'd been putting a few other bugs in re it so had forgotten to clarify!

Is there any more information about the type of certificate that needs to be purchased? The self-hosted guidance only seems to talk about generating your own certificate - https://docs.opensignlabs.com/docs/self-host/docker/run-locally/

Thanks

**Comment by andrew-opensignlabs** [comment]
I have just updated the documentation.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/99281b10-a55e-43c6-bed5-33a245907094">
