### ISSUE TITLE
Cannot read properties of undefined (reading 'roundedStep') - trying to create document and sign on app.opensignlabs.com

### ISSUE THREAD

**Issue by maoo** [OpenSignLabs/OpenSign#121]
Steps to reproduce:
1. Sign up on app.opensignlabs.com
2. Create a document
3. Add 2 signers (plus mandatory fields), one of which is yourself (current user)
4. Add placeholders in 2 different pages for Signatures and Stamps
5. Finish the document
6. When asked to sign immediately the document, say `Yes`

At this point I'd have expected to be redirected to the document signature screen, but instead, the following error was shown: `Cannot read properties of undefined (reading 'roundedStep')`

<img width="1435" alt="Screenshot 2023-11-02 at 11 34 39" src="https://github.com/OpenSignLabs/OpenSign/assets/327285/7c04bb2f-9e9e-41fb-b638-34c2a7b3f9af">

**Comment by nxglabs** [comment]
@maoo Thanks for reporting the issue. It was fixed in v1.0.1 that was released a few hours ago. We have changed the code merge process to avoid issues like this in future.

**Comment by nxglabs** [comment]
@all-contributors add @maoo for bug
