### ISSUE TITLE
[Bug]: Unable to login

### ISSUE THREAD

**Issue by santosh2494** [OpenSignLabs/OpenSign#1212]
### Issue Description

Have configured opensign using docker-compose and able to access the home page on https://localhost:3000 but not on HTTPs://localhost:3001 with which we're unable to see register option to create the users. 
Please suggest If anything needs to be changes in configuration file.s. 

### Expected Behavior

Need to see register page 

### Current Behavior

No option register for new users

### Steps to reproduce

http://localhost:3001

### Screenshots of the issue(optional)

![Opensign](https://github.com/user-attachments/assets/7b9ec655-5c05-43b0-a09e-b18e404a4378)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Ubuntu 20.04

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.1.0

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by wardverduyn** [comment]
Is this a known issue? @andrew-opensignlabs

**Comment by andrew-opensignlabs** [comment]
It should be accessible on port 3001; otherwise, it indicates that your installation wasn't completed correctly. Port 3000 is reserved for internal use and will be blocked in future versions.

**Comment by vantzs** [comment]
I am using nginx proxy manager to access opensign without caddy. I followed the installation instructions and am accessing port 3001 from my nginx proxy config.

I too am missing the option to register.
![image](https://github.com/user-attachments/assets/911acfb4-1653-4c2e-8974-951209aaa09c)
![image](https://github.com/user-attachments/assets/24716321-8fc0-4beb-899a-565eab31056c)
![image](https://github.com/user-attachments/assets/d8d4b046-71f0-4cd9-88cb-99f5fb128212)

Additionally https://opensign.mspnerd.com/ should take you to the default page without registration options. Unfortunately I already have over 80 containers using nginx proxy and can't use caddy as nginx is already bound to 80 and 443. Any ideas?

**Comment by reddexx** [comment]
@andrew-opensignlabs Many who use the container version here have the problem, we get no possible solution to this problem!

After 1 month a solution should be worth mentioning!

I would like to test Opensign, but this will not be possible

**Comment by PereProteus** [comment]
So glad I found this. Caddy is ok but i have it in front of cloudflare instead, so ive removed caddy from a docker build. I've been tearing my hair out for a couple of hours trying to get a registration page, no matter how i set it up, it doesnt work. How do you get that page without caddy. I'd love to test the product as well.

**Comment by swyliealeon** [comment]
Having the same issue here, is there a fix for this or are we just giving up on opensign working?

**Comment by reddexx** [comment]
@swyliealeon 
well i haven't had time for a while but it doesn't seem to interest the developer (@andrew-opensignlabs) either, so i'm looking for another software as a solution

I would have liked to test it, but there's no point if none of the devs are interested

I think they are more focused on what makes money

although I am supposed to find a solution for my company, but without a presentation, nothing works

**Comment by swyliealeon** [comment]
@reddexx thats exactly what they are focused on, and as a company they should be focused on what makes them money.  Ironically, I was going to use this self-hosted to show off before we went with the enterprise plan so I guess it probably ended up costing them money.  Anyways, I reached out to them and their answer was essentially you are doing something wrong go read the documentation.

**Comment by reddexx** [comment]
To me? Iam not the developer 🤣

**Comment by andrew-opensignlabs** [comment]
@reddexx @swyliealeon 
Our self-host community is most active on Discord. Please join our [discord server](https://discord.com/invite/xe9TDuyAyj) if you want quick help from the community.

Please share your browser logs & docker console logs on discord community.

**Comment by juanfranp16** [comment]
For anyone wondering how to run it behind nginx instead of the default cabby proxy, you dont have to modify the REACT_APP_APPID , APP_ID and appNAME variables in your .env.prod file. You cand modify the rest of them as you like.

And in your nginx conf file add the following code

```
location / {
  proxy_pass http://IP_SERVER:3000;
  -- 
  # Your own conf
  --
}

location /app {
  proxy_pass http://IP_SERVER:8080;

 -- 
  # Your own conf
  --
}
```

**Comment by decoderzhub** [comment]
Hi @santosh2494 @vantzs @reddexx @swyliealeon @PereProteus @juanfranp16 

I know this has been an open problem for a while and it took me every bit of two weeks to figure out how to set this up with an alternative reverse-proxy... So I'm posting how to get it to work with nginx using an IP instead of domain name/localhost.  We will be using example local ip 10.0.0.62

first you will want to modify your files:

### **.env.prod**
```
HOST_URL=https://10.0.0.62
PUBLIC_URL=https://10.0.0.62:3001
```

### **docker-compose.yml**

For your server change the environment variables

```
- SERVER_URL=${HOST_URL:-https://10.0.0.62:3001}/api/app
- PUBLIC_URL=${HOST_URL:-https://10.0.0.62:3001}
```

####  replace caddy with  nginx container

```
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "3002:443"  # exposing new secure port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - client
      - server
    networks:
      - app-network
```

## Create your own nginx.crt & nginx.key

Run this command in the root directory to generate the cert and key

```
openssl req -x509 -nodes -days 825 \
  -newkey rsa:2048 \
  -keyout nginx.key \
  -out nginx.crt \
  -config openssl-ip.cnf

```

create a folder in root directory named "certs" and place both cert and key in this folder

![Image](https://github.com/user-attachments/assets/d118bb6c-ebd6-4b61-af1c-4bca1d1f8e8e)

### update nginx.conf

```
server {
    listen 443 ssl;
    server_name 10.0.0.62:3002;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    location / {
        proxy_pass http://client:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://server:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    }

}

```
This routes to the server similar to caddy

Now run

`docker compose up -d`

You may now access the addadmin route to login and by accessing the OpenSignServer.

[https://10.0.0.62:3002](https://10.0.0.62:3002)

![Image](https://github.com/user-attachments/assets/eb50fd3a-dae5-4fbd-bc1d-043b4e4f0d3f)

I use Synology for my reverse-proxy so I just point it to the it

![Image](https://github.com/user-attachments/assets/30a27b99-e915-4003-a775-db77df6e97a9)

Then you can access it at the assigned hostname

![Image](https://github.com/user-attachments/assets/2ac5da0c-31e2-4fcd-8f6f-13633575dfc1)

**Comment by vy0vb17** [comment]
> I managed to get OpenSign working behind NPM Plus (Nginx Proxy Manager Plus) without using the bundled Caddy container, so I'm sharing the configuration in case it helps anyone facing the same issue.
>
> My setup is:
>
> * OpenSign client and server running as Docker containers 
> * MongoDB running on the same Docker network
> * NPM Plus web GUI running on a separate reverse-proxy VM
> * OpenSign client exposed internally on port `3000`
> * OpenSign server exposed internally on port `8080` (`8080:8080`)
> * HTTPS certificate handled by NPM Plus
> * Public/internal URL: `https://opensign.example.com`
>
> Initially, the OpenSign frontend loaded correctly, but it always displayed the "Welcome back" login page. Going to `/addadmin` did not allow me to create the first administrator, even though MongoDB confirmed that both `_User` and `contracts_Users` contained `0` users.
>
> The OpenSign backend itself was healthy:
>
> ```bash
> curl -i http://127.0.0.1:8080/app/health
> ```
>
> returned:
>
> ```text
> HTTP/1.1 200 OK
> {"status":"ok"}
> ```
>
> while:
>
> ```bash
> curl -i http://127.0.0.1:8080/api/app/health
> ```
>
> returned `404 Cannot GET /api/app/health`.
>
> This helped identify the actual issue: the `/api` prefix must be stripped before forwarding requests to the OpenSign server, just like the official Caddy configuration does.
>
> I initially tried using an NPM Plus Custom Location for `/api/` together with:
>
> ```nginx
> rewrite ^/api/(.*)$ /$1 break;
> ```
>
> but this did NOT work correctly in my setup.
>
> What finally fixed it was removing the `/api/` Custom Location and adding the following directly to the 'Advanced' configuration of the OpenSign Proxy Host in NPM Plus:
>
> ```nginx
> location ^~ /api/ {
>     proxy_pass http://OPEN_SIGN_DOCKER_HOST_IP:8080/;
>
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
>
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>
>     proxy_redirect off;
> }
> ```
>
> **The trailing slash in `proxy_pass` is important:**
>
> ```nginx
> proxy_pass http://OPEN_SIGN_DOCKER_HOST_IP:8080/;
> ```
>
> With:
>
> ```nginx
> location ^~ /api/
> ```
>
> this makes Nginx forward:
>
> ```text
> /api/app/...
> ```
>
> to the OpenSign server as:
>
> ```text
> /app/...
> ```
>
> which is what OpenSign expects.
>
> My main NPM Plus Proxy Host still forwards normal traffic to:
>
> ```text
> http://OPEN_SIGN_DOCKER_HOST_IP:3000
> ```
>
> so the resulting routing is essentially:
>
> ```text
> https://opensign.example.com/
>     |
>     +-- /          -> OpenSign client :3000
>     |
>     +-- /api/*     -> OpenSign server :8080
>                       (/api prefix stripped)
> ```
>
> I also configured OpenSign with:
>
> ```env
> HOST_URL=https://opensign.example.com
> PUBLIC_URL=https://opensign.example.com
>
> REACT_APP_APPID=opensign
> REACT_APP_SERVERURL=https://opensign.example.com/api/app
>
> MONGODB_URI=mongodb://opensign-mongo:27017/OpenSignDB
> PARSE_MOUNT=/app
> USE_LOCAL=true
> ```
>
> with `MASTER_KEY` set to a strong random secret.
>
> After applying the NPM Plus configuration, this test:
>
> ```bash
> curl -i https://opensign.example.com/api/app/health
> ```
>
> finally returned:
>
> ```text
> HTTP/1.1 200 OK
> {"status":"ok"}
> ```
>
> and visiting:
>
> ```text
> https://opensign.example.com/addadmin
> ```
>
> successfully displayed the OpenSign initial administrator setup page.
>
> So in my case OpenSign itself, MongoDB, and the database migrations were all working correctly. The issue was specifically reproducing Caddy's `/api/*` path handling when using NPM Plus as an external reverse proxy.
>
> Hopefully this saves someone else a few hours of troubleshooting!

**Comment by melfina** [comment]
> > I managed to get OpenSign working behind NPM Plus (Nginx Proxy Manager Plus) without using the bundled Caddy container, so I'm sharing the configuration in case it helps anyone facing the same issue.
> > My setup is:
> > 
> > * OpenSign client and server running as Docker containers
> > * MongoDB running on the same Docker network
> > * NPM Plus web GUI running on a separate reverse-proxy VM
> > * OpenSign client exposed internally on port `3000`
> > * OpenSign server exposed internally on port `8080` (`8080:8080`)
> > * HTTPS certificate handled by NPM Plus
> > * Public/internal URL: `https://opensign.example.com`
> > 
> > Initially, the OpenSign frontend loaded correctly, but it always displayed the "Welcome back" login page. Going to `/addadmin` did not allow me to create the first administrator, even though MongoDB confirmed that both `_User` and `contracts_Users` contained `0` users.
> > The OpenSign backend itself was healthy:
> > curl -i http://127.0.0.1:8080/app/health
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > returned:
> > ```
> > HTTP/1.1 200 OK
> > {"status":"ok"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > while:
> > curl -i http://127.0.0.1:8080/api/app/health
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > returned `404 Cannot GET /api/app/health`.
> > This helped identify the actual issue: the `/api` prefix must be stripped before forwarding requests to the OpenSign server, just like the official Caddy configuration does.
> > I initially tried using an NPM Plus Custom Location for `/api/` together with:
> > rewrite ^/api/(.*)$ /$1 break;
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this did NOT work correctly in my setup.
> > What finally fixed it was removing the `/api/` Custom Location and adding the following directly to the 'Advanced' configuration of the OpenSign Proxy Host in NPM Plus:
> > location ^~ /api/ {
> >     proxy_pass http://OPEN_SIGN_DOCKER_HOST_IP:8080/;
> > 
> >     proxy_set_header Host $host;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     proxy_set_header X-Forwarded-Proto $scheme;
> > 
> >     proxy_http_version 1.1;
> >     proxy_set_header Upgrade $http_upgrade;
> >     proxy_set_header Connection "upgrade";
> > 
> >     proxy_redirect off;
> > }
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **The trailing slash in `proxy_pass` is important:**
> > proxy_pass http://OPEN_SIGN_DOCKER_HOST_IP:8080/;
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With:
> > location ^~ /api/
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this makes Nginx forward:
> > ```
> > /api/app/...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the OpenSign server as:
> > ```
> > /app/...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is what OpenSign expects.
> > My main NPM Plus Proxy Host still forwards normal traffic to:
> > ```
> > http://OPEN_SIGN_DOCKER_HOST_IP:3000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so the resulting routing is essentially:
> > ```
> > https://opensign.example.com/
> >     |
> >     +-- /          -> OpenSign client :3000
> >     |
> >     +-- /api/*     -> OpenSign server :8080
> >                       (/api prefix stripped)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also configured OpenSign with:
> > HOST_URL=https://opensign.example.com
> > PUBLIC_URL=https://opensign.example.com
> > 
> > REACT_APP_APPID=opensign
> > REACT_APP_SERVERURL=https://opensign.example.com/api/app
> > 
> > MONGODB_URI=mongodb://opensign-mongo:27017/OpenSignDB
> > PARSE_MOUNT=/app
> > USE_LOCAL=true
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with `MASTER_KEY` set to a strong random secret.
> > After applying the NPM Plus configuration, this test:
> > curl -i https://opensign.example.com/api/app/health
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > finally returned:
> > ```
> > HTTP/1.1 200 OK
> > {"status":"ok"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and visiting:
> > ```
> > https://opensign.example.com/addadmin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > successfully displayed the OpenSign initial administrator setup page.
> > So in my case OpenSign itself, MongoDB, and the database migrations were all working correctly. The issue was specifically reproducing Caddy's `/api/*` path handling when using NPM Plus as an external reverse proxy.
> > Hopefully this saves someone else a few hours of troubleshooting!

Thanks so much for sharing. I had the following issue- "Unable to connect to the OpenSign server. If you are self-hosting OpenSign, please ensure that all the steps in the documentation have been followed correctly. If you're running OpenSign locally, you might be accessing it through an incorrect port number." 

Adding the regular expression modifier `^~` near the beginning of the location block and putting slash `/` at end of the address/path in the proxy_pass directive fixed the issue and took me to initial administrator setup page. In my case, I am using the native Nginx in a Docker container and it is in a custom network with my OpenSign server and client and MongoDB. This is what my block looked like in the end-

```
location ^~ /api/ {
            proxy_pass http://server_name:8080/;
            .....
        }
```

By the way, @vy0vb17, these two curl commands are the same here, not sure if that's what you meant.

> > The OpenSign backend itself was healthy:
> > curl -i http://127.0.0.1:8080/app/health
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > returned:
> > ```
> > HTTP/1.1 200 OK
> > {"status":"ok"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > while:
> > curl -i http://127.0.0.1:8080/api/app/health
> >     
> >
