### ISSUE TITLE
Option to obtain token in connection section missing in version 2.3.2

### ISSUE THREAD

**Issue by andriufit** [OpenSignLabs/OpenSign#1231]
Hello everyone,

I've noticed that after updating to version 2.3.2, the option to obtain the token in the connection section is no longer available. This token is essential for interacting with the API, so its absence is affecting the workflow that relies on this functionality.

I followed the installation method outlined in the documentation for self-hosted environments. Additionally, there are no errors appearing in Docker or on the web interface.

I would like to know if this is an intentional change in this version or if it is an error. If it is intentional, is there an alternative method to obtain the token in this version?

Thank you!

**Comment by andrew-opensignlabs** [comment]
@andriufit APIs are not a part of the free self-hosted version. That option was briefly present during beta phase. It has long been removed from free self-hosted version.
