### ISSUE TITLE
Feature Request: Branding

### ISSUE THREAD

**Issue by bobvandevijver** [OpenSignLabs/OpenSign#1257]
### Feature Title

Branding

### Feature Description

I'd like to use custom styling on my self hosted instance to be able to let users know that they are accessing something from our brand. Things like logo's, style colours etc.

### What type of feature are you requesting?

UI/UX Improvement

### Importance

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by Zathiel** [comment]
Hey @bobvandevijver 

Thanks for writing this PR 

Let me ask the dev team about that and I'm coming back to you as soon as possible

**Comment by nxglabs** [comment]
This feature is available on paid version. Please mail us on hello@opensignlabs.com
