### ISSUE TITLE
UI layout issue after signing a document from mobile

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#126]
![image](https://github.com/OpenSignLabs/OpenSign/assets/5486116/123d2289-7ae3-4fe7-b08a-cb5a43b49547)

**Comment by rishabjasrotia** [comment]
Hello @nxglabs @andrew-opensignlabs 
I have handled this issue in #177

**Comment by rishabjasrotia** [comment]
Hello @raktima-opensignlabs I worked an raised PR for this issue.

**Comment by raktima-opensignlabs** [comment]
@nxglabs can you please close this PR
