### ISSUE TITLE
[Bug]: Email configuration issues

### ISSUE THREAD

**Issue by kobenguyen1997** [OpenSignLabs/OpenSign#1375]
### Issue Description

I'm trying to use Office 365 as a custom SMTP provider to send notifications via email for electronic signatures.

I edited the .env.prod file according to the OpenSign documentation to add the SMTP credentials. After configuring, I ran docker compose stop and docker compose start --force-recreate to force Docker to re-read the configuration and recreate the containers, but nothing happened.

There were similar cases like: [#1080](https://github.com/OpenSignLabs/OpenSign/issues/1080) and [#1324](https://github.com/OpenSignLabs/OpenSign/issues/1324) but I couldn't find my answer there. 

### Expected Behavior

Able to send email notifications after signing.

### Current Behavior

No email notification received after signing.

### Steps to reproduce

Edit the .env.prod file

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Windows 10

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

latest

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
Can you share the logs from console?

**Comment by andrew-opensignlabs** [comment]
I am assuming this issue was resolved.
