### ISSUE TITLE
Feature Request: Option to sign the whole document 

### ISSUE THREAD

**Issue by DunklerPhoenix** [OpenSignLabs/OpenSign#1380]
### Feature Title

Fully signed document 

### Feature Description

At the moment some viewers like LibreOffice show the message that the documents generated by opensign are only partially signed. It would be great if there can ne an option to sign all elements inside the PDF (like form fields, images etc) that are not added by opensign

### What type of feature are you requesting?

UI/UX Improvement

### Importance

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
We have added this feature to our roadmap. This wont be available anytime soon(at least within this quarter). I will update about the progress. Closing the issue for now.
