### ISSUE TITLE
Feature Request: Add informations for persistant storage to documentation

### ISSUE THREAD

**Issue by DunklerPhoenix** [OpenSignLabs/OpenSign#1381]
### Feature Title

-

### Feature Description

Please provide informations in the documentation to mount the file/file path for persistant storage of documents in a docker volume if local storage is used.

### What type of feature are you requesting?

Performance / Optimization

### Importance

Medium

### Additional Context

I was wondering at first why documents are shown im the ui, but not available anymore.

Example
```
    volumes:
      - opensign_docs:/usr/src/app/files/files
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
We have modified the config to make the docker volume persistent in the latest version. Note that 'use_local' variable should not be set to 'true' in production, its already mentioned in the documentation.
