### ISSUE TITLE
Feature Request: Global Footer Watermark

### ISSUE THREAD

**Issue by DunklerPhoenix** [OpenSignLabs/OpenSign#1383]
### Feature Title

Global Custom Footer Watermark

### Feature Description

Please provide an option to define a custom watermark that get globally added to the footer of each generated document.
With this I can e.g. set up an information to a validation tool, a site where the viewers of the document can get the CA Certificates from or specific informations about my instance.

### What type of feature are you requesting?

Other

### Importance

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
After internal discussions, we’ve decided that this feature won’t be included in our roadmap for at least the next two quarters.
