### ISSUE TITLE
Change report title from "InProgress Document" to "In-progress documents"

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#14]
<img width="689" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/a205ffe2-da77-43f4-a55d-5bcaa7628e64">

**Comment by ajakov** [comment]
Can I take this?

**Comment by nxglabs** [comment]
@ajakov sure. Assigned it to you.

**Comment by therefat** [comment]
assignee me

**Comment by ajakov** [comment]
Hey @nxglabs sorry to bother you, but did you register as a maintainer on hacktoberfest.com?
I am getting `Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. ` status on my PR.

**Comment by nxglabs** [comment]
It might be because you had crated a PR in your own forked repo.
Are you sure you are not trying to submit that to hacktoberfest?
We are already registered with Hacktoberfest.

**Comment by nxglabs** [comment]
@all-contributors please add @ajakov  for code

**Comment by ajakov** [comment]
> It might be because you had crated a PR in your own forked repo. Are you sure you are not trying to submit that to hacktoberfest? We are already registered with Hacktoberfest.

Ah, I can't believe I did that! Oh well ... :)
Thank you for clarifying.
