### ISSUE TITLE
[Bug]: 1-Click Install takes me to the "Welcome back" page

### ISSUE THREAD

**Issue by burmkiller** [OpenSignLabs/OpenSign#1403]
### Issue Description

I've followed the steps thoroughly and added all the needed environment variables on DO + created a managed DB for mongodb and attached it to the app platform project, yet I'm still being redirected to the welcome back page
<img width="921" alt="image" src="https://github.com/user-attachments/assets/b695f005-c7a1-4577-9bae-a4a7469e5201">
Is there any extra step that I missed that the documentation doesn't cover?

### Expected Behavior

Being redirected to the registration wizard

### Current Behavior

<img width="921" alt="image" src="https://github.com/user-attachments/assets/cf41a8f2-862c-4cca-bed3-15ecdcd88b12">

### Steps to reproduce

- Click on the button to create all the instances on DO
- Fill up the required environment variables
- Head to the generated link by DO

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

latest version

### What environment are you seeing the problem on?

Staging (staging-app.opensignlabs.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
Can you share the logs from your browser console and network tab?
