### ISSUE TITLE
Fix email notification typos

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#15]
![image](https://github.com/OpenSignLabs/OpenSign/assets/5486116/4335f722-294f-4b0d-9e31-0af7cb3e3c24)

Sender should be "OpenSign™".
Document title(MOU between Apple & Tesla) should be in bold.
Space before document title is missing.
The subtitle should be "Document signed successfully" instead of "Document sign successfully".

**Comment by BuilderPrid** [comment]
Hey! I would like to work on this. Can you assign this to me?

**Comment by nxglabs** [comment]
Done. Don't forget to star our repo.

**Comment by LaThanhTrong** [comment]
Can I be assigned to this issue aswell?

**Comment by nxglabs** [comment]
@all-contributors please add @BuilderPrid for code

**Comment by BuilderPrid** [comment]
@nxglabs Thanks a lot for adding me as an contributor. It has been an honour and pleasure to be a part of this digitalization.

**Comment by nxglabs** [comment]
You completely deserve it bro. Let's spread the word and make OpenSign the best Document Signing platform in the world. Cheers!
