### ISSUE TITLE
Question, I can't get "Enable OTP Verification" to show when requesting signatures 

### ISSUE THREAD

**Issue by ovargasp** [OpenSignLabs/OpenSign#1525]
I recently discovered your project, and so far is great, but I'm having a hard time with the OTP verification to sign a file.

I'm running it selfhosted using docker, I already have everything configured but when I go to Request Signatures and open the Advanced Options, to Enable OTP verification, I don't get/see that option, so I'm kind of lost because I think I have all that's need it to run it, and everything else is working and people get to sign the documents, but this an the template's public signing option,  I don't know those are related. 

Any help is appreciated. 
 
Thanks and happy holidays

Expected Behavior : Go to Request Signatures, open advanced options, and see/mark the Enable OTP verification.

Current Behavior : Go to Request Signatures, open advanced options, no Enable OTP verification option in Security Settings.

Steps to reproduce: get docker image latest, generate a new p12 certificate with a new pass phrase, update .env.prod with those, add mail server settings, , run docker compose up, go to Request Signatures, etc...

Screenshots of the issue(optional)
No response

Operating System [e.g. MacOS Sonoma 14.1, Windows 11]: ubuntu server 22.04,

What browsers are you seeing the problem on?: Brave, Chrome

What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]: 2.6.0 Docker Image

What environment are you seeing the problem on?: Docker

**Comment by andrew-opensignlabs** [comment]
@ovargasp OTP verification feature is not a part of the free open source version.

**Comment by ovargasp** [comment]
Ok that explains it, thanks for the replay

**Comment by JohnMacOB** [comment]
@andrew-opensignlabs 
Thanks for the sw!! it's epic!

Have you considered adding this feature?
It would be possible to implement.
Feels like feature gating to me?
