### ISSUE TITLE
Access to PDF in Digital Ocean blocked by CORS policy

### ISSUE THREAD

**Issue by maoo** [OpenSignLabs/OpenSign#159]
## Description
After signing a document, the page shows the error (twice) `Failed to load PDF file.`. Inspecting the browser console, I found a probably relevant log:
```
Access to fetch at 'https://foo.nyc3.digitaloceanspaces.com/exported_file_4627_0000-00-00T00%3A45%3A43.344Z.pdf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

## Steps to reproduce

1. Run with docker compose
```
rm -rf apps/OpenSign/public/mfbuild
cd microfrontends/SignDocuments && npm install && npm run build && cd ../..
cp .env.local_dev .env
docker compose up -d
```

2. Create account
4. New Document > Sign yourself
5. Submit signed document

## Expected behaviour

The preview of the signed PDF

## Actual behaviour

Error message `Failed to load PDF file.`, shown twice (in the `Pages` left column and in the main column)

<img width="895" alt="Screenshot 2023-11-08 at 20 51 30" src="https://github.com/OpenSignLabs/OpenSign/assets/327285/924605d6-6d5b-4d8b-98f0-8e3f8d09bf4d">

**Comment by nxglabs** [comment]
You need to add "http://localhost:3000" to your digital ocean bucket cors settings.
Read more on below link -
https://docs.digitalocean.com/products/spaces/how-to/configure-cors/

**Comment by maoo** [comment]
Thanks @nxglabs ! Is it worth adding some text at the bottom of https://github.com/OpenSignLabs/OpenSign/blob/staging/INSTALLATION.md ? Happy to work on a PR

**Comment by nxglabs** [comment]
@maoo please go ahead and raise a PR.

**Comment by maoo** [comment]
@nxglabs - https://github.com/OpenSignLabs/OpenSign/pull/160 is ready for review.

**Comment by maoo** [comment]
Confirming that - after properly configuring CORS - OpenSign app behaves as expected. Closing issue.

**Comment by bigbeka** [comment]
@maoo I am getting the same error, but with local storage `true`. This is happening both to locally hosted instances and to fresh install of OpenSign on Digital Ocean (with local storage enabled).

I detailed the issue here #1138, could your solution have something to do with local storage?

**Comment by maoo** [comment]
Thanks for the update @bigbeka - I'm not using OpenSign anymore, we ended up building a custom solution. Unfortunately I don't have an environment in place to test the fix.

**Comment by bigbeka** [comment]
@maoo Thanks for letting me know. I will keep looking for a solution.

**Comment by bigbeka** [comment]
@andrew-opensignlabs, please have a look at my #1138 issue, It is nothing to do with CORS or S3 storage.
