### ISSUE TITLE
Issue with multiple annotations in single file

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#164]
Steps to re-produce -

- Upload a PDF using "Sign yourself" flow
- Draw a signature at 2 different locations
- Submit

The screen stucks at the loader displaying "this might take some time".

Expected outcome -
It should successfully sign the document

**Comment by rishabjasrotia** [comment]
Hello @nxglabs 
The issue is not reproduced when applied similar procedure.

**Comment by nxglabs** [comment]
@rishabjasrotia the issue is already resolved. Sorry for not closing it earlier.
