### ISSUE TITLE
Transparent PNG signature issue

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#165]
When a transparent PNG image is uploaded for annotation, the background turns black after signing.
It should turn white.

**Comment by PG-257811** [comment]
Hi, @nxglabs 
If this issue is yet not resolved. I would like to work on this, Please assign it to me.

**Comment by nxglabs** [comment]
@PG-257811 sorry, a pull request has already been submitted by @raktima-opensignlabs 

We will be creating new issues/feature requests soon on which you can work.

**Comment by PG-257811** [comment]
Oky np @nxglabs. Thanks for the update, Looking forward to contribute in this amazing project.
