### ISSUE TITLE
Improve the filename of the downloaded file

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#167]
After signing a document, currently the document name is generated as below -
"a long document name_signed_by_OpenSign™.pdf"

The filename will look more consistent if it is -
"a_long_document_name_signed_by_OpenSign™.pdf"

**Comment by rishabjasrotia** [comment]
Assign me this issue @nxglabs

**Comment by rishabjasrotia** [comment]
Hello @nxglabs 
PR raised #176

**Comment by andrew-opensignlabs** [comment]
@rishabjasrotia 
Can you join us on Discord?

https://discord.com/invite/xe9TDuyAyj

**Comment by rishabjasrotia** [comment]
Yes sure will join.

**Comment by rishabjasrotia** [comment]
We can close this Issue since PR is merged.

**Comment by andrew-opensignlabs** [comment]
@rishabjasrotia we have download option in multiple flows. It might not be solved at all places. Let me test it thoroughly before closing.

**Comment by raktima-opensignlabs** [comment]
@nxglabs close issue #167
