### ISSUE TITLE
Improve popup that comes on viewing a "completed" document

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#168]
<img width="1438" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/3465d4eb-c5eb-462f-a350-445df0c125d6">

The popup should be vertically & horizontally centre aligned and background rgba(0, 0, 0, 0.75) should apply.

**Comment by jasonzubiate** [comment]
Hi what is the component name, looking for it in the codebase

**Comment by rishabjasrotia** [comment]
Hello @nxglabs 
You want to align this popup based on PDF center or display screen center?

Like below:
![image](https://github.com/OpenSignLabs/OpenSign/assets/33950743/702af9f5-f30e-4c19-9e8a-2155dd934ab7)

**Comment by nxglabs** [comment]
@rishabjasrotia i guess it will look better if its shown in center of PDF.

**Comment by rishabjasrotia** [comment]
Okay i will correct the styling for this component.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs ,
I worked on this issue.
Here is below output:
![image](https://github.com/OpenSignLabs/OpenSign/assets/33950743/953baf3a-8141-4a4b-a83a-f9593b8d98b5)

**Comment by rishabjasrotia** [comment]
Hello @nxglabs PR raised #177 177.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs ,
I have raised new PR to include only changes related to this issue.
#188

**Comment by rishabjasrotia** [comment]
Hello @nxglabs 
The background is needed to be applied to background screen?
**background rgba(0, 0, 0, 0.75)** 

cc @raktima-opensignlabs

**Comment by nxglabs** [comment]
@rishabjasrotia yes we need to grey out the background when the popup is visible.

**Comment by rishabjasrotia** [comment]
I think you need modal backdrop
https://mdbootstrap.com/docs/standard/extended/modal-backdrop/

**Comment by rishabjasrotia** [comment]
Here is output:
![image](https://github.com/OpenSignLabs/OpenSign/assets/33950743/629de1d0-a4a7-4057-b122-b18cb109b3e9)

@nxglabs
