### ISSUE TITLE
While dragging sign placeholder in mobile view the drawbox pops up unexpectedly

### ISSUE THREAD

**Issue by andrew-opensignlabs** [OpenSignLabs/OpenSign#170]
![image](https://github.com/OpenSignLabs/OpenSign/assets/148278535/82c0a637-25e6-4451-b5af-aab676f8c1f8)

Even when the user does no intend to click the placeholder the drawpad pops open when he tries to adjust the position or size of it.

**Comment by nxglabs** [comment]
@rishabjasrotia can you help us with this issue?

**Comment by rishabjasrotia** [comment]
Yes sure I will check this problem.
We need to handle the event for onClick and onDrag.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs,
The code is written to display signature pad on following criteria:

1. When signature button is clicked => It drops Signature placeholder in PDF => **Then it instantly opens signature pad** 
2. When signature is dragged => **It again opens signature pad.** 

I think we should only open Signature pad when user clicks on the placeholder?

If you agree I have solution for issue.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs
PR is raised #197 197

**Comment by raktima-opensignlabs** [comment]
@nxglabs close issue #170
