### ISSUE TITLE
Error when trying to use saved Signature!

### ISSUE THREAD

**Issue by rishabjasrotia** [OpenSignLabs/OpenSign#204]
Steps to Reproduce:

- Go to Settings -> My Signature -> Draw & Save your signature.
- Select Sign Yourself Signature
- Add signature using the saved my signature
- Try to Resize it and click on finish

Error:
![image](https://github.com/OpenSignLabs/OpenSign/assets/33950743/d1bc5ee8-5acd-49cb-8520-7737de267097)

Error Location:
File: SignYourSelf.js
```
    // Convert to JPEG by using the canvas.toDataURL() method
                  const jpegBase64Data = canvas.toDataURL("image/jpeg");
```

**Comment by raktima-opensignlabs** [comment]
Hello, @rishabjasrotia, we're finding it difficult to create this issue. Could you send us a demo video to guide us through the steps?

**Comment by rishabjasrotia** [comment]
Hello @raktima-opensignlabs 

please find the video showing steps to reproduce error.

[screen-capture.webm](https://github.com/OpenSignLabs/OpenSign/assets/33950743/b1846415-6df9-41ce-8306-710a06041ac1)

**Comment by rishabjasrotia** [comment]
Hello @raktima-opensignlabs ,
I have identified the actual root cause.
I will raise PR.
