### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by RajGuru878** [OpenSignLabs/OpenSign#218]
![Screenshot from 2023-11-22 13-02-35](https://github.com/OpenSignLabs/OpenSign/assets/143713220/7765b0ce-4dbf-45c2-b762-89ec2920b841)
Hello,
After successful installation, I am unable to login due to credentials. I haven't mentioned login details at the time of installation also it was not asked. Please guide me on this anybody. 
Thank you,

**Comment by rishabjasrotia** [comment]
Hello @RajGuru878 ,
You can create new account.

**Comment by RajGuru878** [comment]
@rishabjasrotia 
I hosted it on self. And I am unable to create new account there.

**Comment by viniciusbrun-dev** [comment]
Hi! I'm facing the same issue. On v2.0.0 there is no "create account" button. Is there a guide to find the default user or a register a new one? 
![image](https://github.com/user-attachments/assets/46e9f0b9-55b2-4352-9705-fd44f7ec8a5a)
