### ISSUE TITLE
The delete button(cross) on "email documents" popup is not aligned properly with email

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#26]
<img width="530" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/a1d317fa-9c4c-41c5-866b-ea5335682dde">

The delete button does not appear in line with the email id on "Email documents" popup that appears after successfully signing a document.

**Comment by soumytiwari** [comment]
I would like to work on it.

**Comment by soumytiwari** [comment]
I am not able to understand🤷‍♀️
could you help me?
How can I open and use this?
And how to see the page (code) you want to fix..

**Comment by nxglabs** [comment]
Follow below steps to quickly run the code locally for working on the React code -

rename .env.example.frontend to .env
cd to /apps/OpenSign folder and run "npm install" command
npm run start to run the frontend locally.

**Comment by abuna1985** [comment]
@nxglabs I can work on this issue. Can you assign it to me please?

**Comment by Abbas-Dev-Axioms** [comment]
I can work on on this issue. Can you assign it to me?

**Comment by abuna1985** [comment]
I will have a pull request sent for this issue by later tonight/tomorrow.
