### ISSUE TITLE
Remove underline that appears on hovering the "Certificate" button

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#28]
<img width="647" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/efa04b2c-67f4-47d0-8ea4-202800883ac0">

Remove underline that appears on hovering the "Certificate" button that appears after a document is successfully signed.

**Comment by Jobin-S** [comment]
I can work on this

**Comment by Jobin-S** [comment]
Can you please share the steps to install in localhost? it is not mentioned in INSTALLATION.MD

**Comment by R4Rohit23** [comment]
I want to contribute, can you please assign this issue to me @nxglabs .

**Comment by andrew-opensignlabs** [comment]
@Jobin-S 

Local installation instructions have been updated.

Follow below steps to quickly run the code locally for working on the React code -

- rename .env.example.frontend to .env
- cd to /apps/OpenSign folder and run "npm install" command 
- npm run start to run the frontend locally

**Comment by Jobin-S** [comment]
Thanks for the update

**Comment by nxglabs** [comment]
@Jobin-S Are you working on this?

**Comment by Jobin-S** [comment]
Yes I am working on it.

Why it is showing ``

**Comment by Jobin-S** [comment]
yes, I am working, I am not getting why the code updating is not reloading live on localhost. I changed the code first no change. so I tried out changing the name of the same button at three places with the same name, `/OpenSign/microfrontends/SignDocuments/src/Component/component/header.js`

**Comment by Jobin-S** [comment]
Do hot reload won't work on this setup? can you please help me to properly setup the frontend? I can do more contributions in future also
