### ISSUE TITLE
Issue when trying to deploy it on kubernetes

### ISSUE THREAD

**Issue by sherlant** [OpenSignLabs/OpenSign#283]
I all,
i try to deploy opensign on kubernetes;
For that, i use cert-manager to provision the pks12 cert, and i have three pods, one for mongodb, one for the opensign client, and one for opensign server.
In addition, i have deploy a service for the client, and an other one for the server, with ingressroutes for both.

The deploy works, but when i try to create an account, the first time i have multiple errors, and i see 502/503 errors on https://opensing-server.my-domain.io/app/functions/usersignup, and after, i have the pop-up "email sending", and the server crash with following error :
```
/usr/src/app/node_modules/parse-server/lib/ParseServer.js:263
          throw err;
          ^

[Error: 140083692836800:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
Stream closed EOF for opensign/opensign-server-69bbb6775f-4pkq6 (opensign-server)
```

in mongodb, the user is created, and the verified mail is false. But i have not any mail. I have try to configure smtp with a local mailcatcher, without authentication, but it doesn't work. I also have try with a real smtp server, with auth, used by other apps correctly, but it doesn't work.

Anyone can help me please ?

Thanks for advance

**Comment by sherlant** [comment]
Hello @rishabjasrotia ! 
i deploy it on a real kubernetes cluster. But i have found the problem. I use a mailgun account with smtp configuration, and the port was 587 and no 465, so this is ok now.

I have another question about opensign. Can i give a .p12 path for the pkcs12 instead of base64 of the file in env var ?

**Comment by rishabjasrotia** [comment]
Yes you can give the path also.

**Comment by nxglabs** [comment]
@sherlant You cant give the path to p12 file, you meed to set the env variable with base64 of it.

**Comment by rishabjasrotia** [comment]
Hello @sherlant is your issue resolved?

**Comment by sherlant** [comment]
Hello !
sorry for the late response.

yes, it's ok for me. Thank you !

**Comment by sherlant** [comment]
Hi All,
sorry for re-open the issue now, but i have tested to implement my deploy with base64 of the path of p12 file in PFX_BASE64 env var, and i have the following error :
```
Err  Error: Too few bytes to read ASN.1 value.
    at _fromDer (/usr/src/app/node_modules/node-forge/lib/asn1.js:504:19)
    at Object.asn1.fromDer (/usr/src/app/node_modules/node-forge/lib/asn1.js:458:15)
    at SignPdf.sign (/usr/src/app/node_modules/node-signpdf/dist/signpdf.js:105:45)
    at SignPDF.signPDF (/usr/src/app/cloud/parsefunction/pdf/SignPDF.min.cjs:1:140)
    at PDF (file:///usr/src/app/cloud/parsefunction/pdf/PDF.min.js:196:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  available: 42,
  remaining: 42,
  requested: 117
}

Result: {"status":"error","message":"Encrypted files are currently not supported!"}
```
Can you help me to fix it ?

Thanks !
