### ISSUE TITLE
[Bug]: Update Twitter icon to X on contact page's social media

### ISSUE THREAD

**Issue by krushnarout** [OpenSignLabs/OpenSign#287]
### Issue Description

The twitter icon has been updated to X on home page but it's still old one on contact-us page.

### Expected Behavior

It should display new X icon.

### Current Behavior

Social media section have old twitter icon.

### Steps to reproduce

1. Got to https://www.opensignlabs.com/contact-us
2.In social media section, the twitter icon is old one.

### Screenshots of the issue(optional)

![Contact-OpenSignLabs-com](https://github.com/OpenSignLabs/OpenSign/assets/129386740/c03662c6-fd27-4669-b8e8-e164ecbca05e)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Windows 11

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

1.0.7-beta

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by BipulLamsal** [comment]
If anyone is not working on it I can resolve this issue

**Comment by krushnarout** [comment]
It's haven't addressed yet, let the owner approve that first, then you can ask for assign you. Btw I'm working on this issue

**Comment by Gowthamk007m** [comment]
I don't know whether someone is working on this issue, but if it's still available, i would love to make a contribution here.

**Comment by Zathiel** [comment]
Hey @krushnarout.

Sorry for the delay 

I will ask the team to have a look on that.

Regards

**Comment by nxglabs** [comment]
This text does not come from the repo so this logo cannot be fixed by contributors.
