### ISSUE TITLE
Fix the popup layout for "Add contact" form under the "Request signatures" flow

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#30]
<img width="1427" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/fe7c55c1-33ee-4182-8267-a08c60e9ceca">

Steps to re-create -
- Navigate to "Request signatures"
- Click the "+" button beside the "Signers" dropdown.

**Comment by JureBl** [comment]
Can you assign me?

**Comment by JureBl** [comment]
What is the best way to start your application. I did npm build followed by npm start and i get uncaught runtime errors. 
Probably I did something wrong, but I also didnt find a documented way to start this application.

**Comment by Piyush07p** [comment]
can u assign it to me

**Comment by shaund16** [comment]
@Piyush07p are you still handling this issue?

**Comment by nxglabs** [comment]
Hey @shaund16 Assigned it to you as well.
Lets see who finishes it first :)

**Comment by rishabjasrotia** [comment]
Hello @andrew-opensignlabs is this issue handled in #108 ?
So we can close it.
