### ISSUE TITLE
Hidden Text - Revealed for specific signers, especially SSN

### ISSUE THREAD

**Issue by EnigmaConsultingIdaho** [OpenSignLabs/OpenSign#302]
### Feature Title

Hidden Text, Selective Signers

### Feature Description

Specifically for use with Social Security Numbers, a subset of Hidden Text that is revealed to selected signers, perhaps only on hover.

The purpose being to have all signers see that the SSN fields are filled, but only allowing them to view their own SSN.

### What type of feature are you requesting?

Security / Compliance

### Importance

High

### Additional Context

Yes, this feature is requested because of real life issue. .sigh.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by Zathiel** [comment]
Hey @EnigmaConsultingIdaho 

I will discuss that with the team and come back to you if we plann to do it 

Regards

**Comment by nxglabs** [comment]
This seems like a great feature but it's too advanced at this stage as there are many important basic features that we are currently building. I have added this to our roadmap but it will surely not be a priority item as of now.
