### ISSUE TITLE
Change the title length limit from 50 characters to 100 characters on "Request signatures form"

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#31]
<img width="1150" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/56756cf5-95e6-4d13-9732-c44e684e63c4">

Steps to re-create:
- Navigate to "Request signatures" from main menu
- Enter a title which is longer than 50 characters

**Comment by parthrc** [comment]
Hey @nxglabs I was testing this and found aFormJson.js file, in that there is the "json form for request signature" section, should I change the value there?

**Comment by nxglabs** [comment]
Yes. You can change the value there and raise a pull request. Will review the changes and let you know if anything needs to be improved.
