### ISSUE TITLE
Change the title of popup that appears after sending out emails from "Request signatures" flow

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#32]
<img width="725" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/ca8fd4c6-6c6b-4c3b-84a9-774f736b90ae">

Steps to re-create:
- Navigate to "Request signatures" from main menu
- Upload a PDF, add signers and submit
- On preview screen add place holders for all signers and click submit

Change the title to "Mails sent"

**Comment by Tashuuuu** [comment]
I want to work on it. Please tell me, change the title to what.

**Comment by nxglabs** [comment]
Change the title to "Mails sent"

**Comment by rishabjasrotia** [comment]
Hello @nxglabs assign it to me
