### ISSUE TITLE
Change the message displayed in signature panel to guest signers when no-default signature is saved

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#34]
<img width="1439" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/d65ab437-2fc4-4cd3-8efa-fb3923de737f">

Change the message from "**You didn't add your default signature yet!**" to "**Click a signature placeholder to start signing the document!**"

Steps to re-create:
- Navigate to "Request signatures" from main menu
- Upload a PDF, add signers and submit
- On preview screen add place holders for all signers and click submit
- Emails will be sent to all signers with a link to sign the document as guest
- When a user clicks the link in order to sign the document, an OTP is sent to his email id
- After entering the OTP he gets to see the above message if no default signature is saved in his account

**Comment by LemonDrop847** [comment]
Would like to try this, can I be assigned?

**Comment by LemonDrop847** [comment]
Where exactly can i find this? Been looking through the code and cant find a reference to this.

**Comment by nxglabs** [comment]
@LemonDrop847 Really sorry for this.
The architecture of OpenSign is based on MicroFrontends.
The source code of the micro-fronted which has this is not yet released.
Really sorry for the confusion. Lets keep this on hold for some time.
We will release the code as early as possible.

**Comment by LemonDrop847** [comment]
Okay. Will have a look again later.

**Comment by nxglabs** [comment]
Source code updated. Let me know if you still face any issues.

**Comment by nxglabs** [comment]
@all-contributors please add @LemonDrop847 for code
