### ISSUE TITLE
Change Body text of OTP email from "Your OTP for LegaDraft verification" to "Your OTP for OpenSign™ verification is:"

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#35]
<img width="1032" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/5486116/5761f78e-6e3a-4622-9a6c-4daa8f52df28">

Steps to re-create:
- Navigate to "Request signatures" from main menu
- Upload a PDF, add signers and submit
- On preview screen add place holders for all signers and click submit
- Emails will be sent to all signers with a link to sign the document as guest
- When a user clicks the link in order to sign the document, an OTP is sent to his email id

**Comment by BuilderPrid** [comment]
Hey @nxglabs. I have had a good look at the repository and would like to work on this. 
Can you assign this to me?

**Comment by nxglabs** [comment]
Hey @BuilderPrid Thanks for your efforts bro.
Lets change the way the world signs documents. Cheers.
