### ISSUE TITLE
Create .env template

### ISSUE THREAD

**Issue by Jobin-S** [OpenSignLabs/OpenSign#39]
Create env template file so that new contributors can can make env from the template

**Comment by nxglabs** [comment]
Added .env.example file on the main branch.

**Comment by nxglabs** [comment]
@all-contributors please add @Jobin-S for doc

**Comment by andrew-opensignlabs** [comment]
@all-contributors please add @Jobin-S for doc

**Comment by andrew-opensignlabs** [comment]
https://github.com/all-contributors please add @Jobin-S for doc

**Comment by andrew-opensignlabs** [comment]
@all-contributors please add @Jobin-S for doc
