### ISSUE TITLE
[Bug]: 404 Error - One Click Digital Ocean Install

### ISSUE THREAD

**Issue by martman0823-2** [OpenSignLabs/OpenSign#460]
### Issue Description

Receiving a 404 Error when visiting the installation

### Expected Behavior

Working site

### Current Behavior

404 Error

### Steps to reproduce

https://opensigndb-bbowy.ondigitalocean.app/

### Screenshots of the issue(optional)

<img width="585" alt="Screen Shot 2024-03-05 at 7 27 19 PM" src="https://github.com/OpenSignLabs/OpenSign/assets/92335314/77463530-0437-4f59-bb6d-800886dab61e">

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

[e.g. MacOS Sonoma 14.1, Windows 11]

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

main

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@martman0823-2 There might be some issue with your configuration. We are working on bringing 1 click install for various cloud providers including digital ocean. It should be live within a week. Request you to wait till then.
