### ISSUE TITLE
[Bug]: Local instance is trying to access S3 bucket with USE_LOCAL=TRUE

### ISSUE THREAD

**Issue by sebyakuya** [OpenSignLabs/OpenSign#607]
### Issue Description

I managed to get a document signed locally but I had to remove everything related to S3, because I was getting mad. 

I've spend most of the time trying to avoid the "Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1" error because it was trying to connect to a non-existing S3 bucket, even though I had the USE_LOCAL variable set to TRUE. I think the problem is with the loading of the getPresignedURL function, which seems to be loaded even with USE_LOCAL=TRUE.

BTW I'm not really sure about why this fails, I'm just sharing the problems I had when trying to run this locally with the current instructions.

PD: Please update the documentation, it's very tough to guess some basic things to start a local instance:

- I didn't know what a Parse server was, I had to guess how to create the first user and adding a role, I had to use parse-dashboard to do it (parse-dashboard --dev --appId opensignstgn --allowInsecureHTTP --masterKey XnAadwKxxByMr --serverURL "http://localhost:8080/app" --appName open_sign_server)
- There's no indication to have the latest node/npm version to be able to make build, it would be nice to have
- The .env.local_dev contains APP_ID=opensign instead of APP_ID=opensignstgn. Once I started using APP_ID=opensignstgn everything was smooth but this specific error message could be more descriptive
- Does apps/OpenSignServer/app.yaml need to be updated if we are using docker-compose up?

### Expected Behavior

If USE_LOCAL is set to TRUE when I go to sign a document it should load the PDF correctly. 

### Current Behavior

A "Failed to load PDF" error appears. I can see requests to a non-existing S3 bucket.

### Steps to reproduce

- Edit .env and set USE_LOCAL=TRUE
- docker-compose up
- Sign yourself menu
- Load a PDF
- Error message appears "Failed to load PDF" on draft page
- Check network tab, see requests to AWS

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Windows 10

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

1.4.2

### What environment are you seeing the problem on?

Dev (localhost or vercel)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@sebyakuya thanks for reporting this. We will be fixing it soon.

**Comment by nxglabs** [comment]
@sebyakuya this issue has been resolved. Can you please check and confirm?

**Comment by sebyakuya** [comment]
Hi,

I've been trying to start from the staging branch but I'm finding the following error:

![image](https://github.com/OpenSignLabs/OpenSign/assets/3855169/8045f068-6e7b-4918-9265-677ca2177529)

I've checked the OpenSignServer has that dependency in the package.json and that it's inside node_modules, I don't know why it's saying that it can't be found.

Steps:

* Ensure you work with the latest NPM version
* git checkout -- .
* Ensure you are in the "staging" branch
* Ensure .env.local_dev has default values
* Make build
* OpenSignServer container fails to start while the other containers are running fine

FYI I've been using tagged branch v1.4.2 these days without any problem which was my main issue, so if you consider this bug is solved or that the issue might come from my local node/npm installation it's fine by me.

**Comment by Zathiel** [comment]
Hey @sebyakuya 

Are you still facing issues with the last release ?

If not i will mark this issue as solved

**Comment by sebyakuya** [comment]
No problem, you can close this issue
