### ISSUE TITLE
[Hacktoberfest]: I can add the animation in the main page using Framer Motion

### ISSUE THREAD

**Issue by Monilprajapati** [OpenSignLabs/OpenSign#61]
I will make it more dynamic and user-friendly by adding animation using framer motion to the main page.

**Comment by Monilprajapati** [comment]
I will make it more dynamic and user-friendly by adding animation using framer motion to the main page.

and if you like it, I will create more issues with adding those types of animations on different pages, like pricing and all.

**Comment by nxglabs** [comment]
@Monilprajapati  Great. Lets give it a try.

**Comment by Monilprajapati** [comment]
Hey @nxglabs I am stuck at this login signup page. How can I go to the home page (where I am going to add animations) without getting signed in? Do I need to set up the backend?

**Comment by Monilprajapati** [comment]
> @Monilprajapati Great. Lets give it a try.

I have solved two other issues on the website: Issues #65 and #67 . Please check those out.

**Comment by nxglabs** [comment]
We are putting together a .env template that will enable you to launch the frontend locally while connecting to backend staging server in a few minutes. This will speed up any development efforts in frontend. Will update you here once changes are pushed.

**Comment by Monilprajapati** [comment]
> We are putting together a .env template that will enable you to launch the frontend locally while connecting to backend staging server in a few minutes. This will speed up any development efforts in frontend. Will update you here once changes are pushed.

How long will it take becuase i need to raised PR before 31 oct for Hacktoberfest.

**Comment by Monilprajapati** [comment]
> > @Monilprajapati Great. Lets give it a try.
> 
> I have solved two other issues on the website: Issues #65 and #67 . Please check those out.

Can you merge those PRs by the EOD? @nxglabs

**Comment by nxglabs** [comment]
@Monilprajapati Check the recently .env.example.frontend file. 

Follow below steps to quickly run the code locally for working on the React code -

- rename .env.example.frontend to .env
- cd to /apps/OpenSign folder and run "npm install" command 
- npm run start to run the frontend locally

**Comment by Monilprajapati** [comment]
> @Monilprajapati Check the recently .env.example.frontend file.
> 
> Follow below steps to quickly run the code locally for working on the React code -
> 
> * rename .env.example.frontend to .env
> * cd to /apps/OpenSign folder and run "npm install" command
> * npm run start to run the frontend locally

I have already set up the frontend but How can i edit that home page? Because when i run it my local host Login page is there but as i have not set up the backend, how can i skip this authentication part?

**Comment by nxglabs** [comment]
Use env.example.frontend file. It will automatically connect to the hosted staging backend. You dont need to setup anything locally. Just sign up and you will be logged in automatically. Note that all the data stored in staging server is temporary. You may might need to sign up frequently.

**Comment by nxglabs** [comment]
@Monilprajapati are you still working on the animation?

**Comment by Monilprajapati** [comment]
> @Monilprajapati are you still working on the animation?

Yes I am. I was just Stuck into some college work. Will do it ASAP!

**Comment by Monilprajapati** [comment]
Can you give me your Discord ID? @nxglabs

**Comment by nxglabs** [comment]
Its already there in the repo homepage.

**Comment by Monilprajapati** [comment]
@nxglabs, I apologize for the delay. My college commitments, including submissions and vivas, have been keeping me occupied. Consequently, I couldn't find the time to work on it. However, I have now successfully set up the project locally. I have raised an issue with adding animation to the document on the website (attached below) in order to make it dynamic. Could you please guide me on how to locate and address this page? In addition to the mentioned tasks, I have identified that I can contribute to other aspects of the website, such as improving the user profile to make it more user-friendly.

Image: 
![image](https://github.com/OpenSignLabs/OpenSign/assets/99136041/4e63ec11-fdd9-47c7-a908-c910c55746c4)

**Comment by andrew-opensignlabs** [comment]
@Monilprajapati we appreciate your commitment to the project. I am closing this issue for now as implementing framer motion in frontend website wont be possible as its not made in react. Though you can initiate a new issue after giving a thought on where you can implement animations in the main app, for example after successfully signing a document or probably on the dashboard.
