### ISSUE TITLE
Beta testers needed : Test OpenSign app & report any bugs that you find

### ISSUE THREAD

**Issue by andrew-opensignlabs** [OpenSignLabs/OpenSign#63]
Help us test our app which is an open source DocuSign alternative.

Steps to follow -
- Create an account at https://www.opensignlabs.com/plans-pricing
- You can select the hosted plan (worth 29.99$/mo). To get it free during beta use coupon code "FREEBETA"
- Use the app to identify any bugs
- Create a new issue at https://github.com/OpenSignLabs/OpenSign/issues/new
- Add screenshots & steps to re-produce wherever necessary

Your newly created issues will be labelled 'hacktoberfest' if accepted.

**Comment by Emm-dev0** [comment]
I would like to work on this please assign it to me

**Comment by Emm-dev0** [comment]
Thanks, Working on it right away.

**Comment by Emm-dev0** [comment]
I have discovered some bugs, but I have created an issue for the one concerning the print button not functioning on mobile 📲 view

**Comment by andrew-opensignlabs** [comment]
Great. Thanks @Emm-dev0 
Do create more issues if you find any.

**Comment by andrew-opensignlabs** [comment]
@all-contributors add @Emm-dev0 for bug

**Comment by Emm-dev0** [comment]
Thank you very much @andrew-opensignlabs
