### ISSUE TITLE
[Bug]: Guest Url Error https:%2F%2Fwww.api-opensign.honey-digital.fr%2Fapp%2F&opensign&contracts

### ISSUE THREAD

**Issue by ugoconsonni** [OpenSignLabs/OpenSign#671]
### Issue Description

The guest URL with "%2F" is not working as the browser interprets "%2F" as "/", leading to a "not found" error on the page. It's recommended to maintain the code's logic by encoding the URL with btoa and decoding it with atob.

Additionally, there is an error with the URL returned by the document creation API. It incorrectly returns the server's URL twice instead of the front-end URL, as shown in the returned data. This suggests that the API's logic for generating the URL needs correction to ensure it points correctly.

### Screenshots of the issue(optional)

<img width="1301" alt="Capture d’écran 2024-05-06 à 04 16 37" src="https://github.com/OpenSignLabs/OpenSign/assets/13661702/8b839acc-a574-4ce0-832c-4cb153ccfcba">

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

1.5.1

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by raktima-opensignlabs** [comment]
@andrew-opensignlabs can you please close this PR
