### ISSUE TITLE
[docs] USAGE document is missing

### ISSUE THREAD

**Issue by lookfirst** [OpenSignLabs/OpenSign#69]
There is a link to a USAGE document, which is now 404. I tried to find it, but didn't have much luck after a few minutes.

**Comment by nxglabs** [comment]
We are currently drafting the document. It will be published soon. Till that time you can refer below video -

https://youtu.be/szYaBZhXZNo?si=faCvuG2ELIL_jBaj

**Comment by nxglabs** [comment]
You can find the documentation on below link-
https://docs.opensignlabs.com

**Comment by lookfirst** [comment]
@nxglabs Thanks for this. You might want to update links as well:

https://github.com/OpenSignLabs/OpenSign/tree/staging?tab=readme-ov-file#usage

https://github.com/OpenSignLabs/OpenSign/blob/staging/USAGE.md

**Comment by nxglabs** [comment]
@lookfirst Updated. Thanks for reporting this.
