### ISSUE TITLE
Document local installation

### ISSUE THREAD

**Issue by delanym** [OpenSignLabs/OpenSign#70]
Complete the installation page to describe installing locally

**Comment by rishabjasrotia** [comment]
Hello @delanym 
I have work on setting up local and also updated document in #103

**Comment by 2-towns** [comment]
Hi @rishabjasrotia 

Yes thanks for the local setup. 

But it still needs quick documentation about the variables to configure, how to generate the `PFX_BASE64`...etc

**Comment by rishabjasrotia** [comment]
Hello @2-towns I have update documentation for PFX generation #139

**Comment by Zathiel** [comment]
Hi.

Docker related issue will be followed in #795
