### ISSUE TITLE
Minio Support ?

### ISSUE THREAD

**Issue by accforgithubtest** [OpenSignLabs/OpenSign#72]
Would be good to have a fully self-hosted version by ditching the s3, and using a the compatible minio api please ?

**Comment by dgeo** [comment]
seems a good idea ! self-hosted with S3 is not very self-hosted :)

**Comment by nxglabs** [comment]
We already support all S3 compatible object storage services. We will update the documentation soon to include instructions for integrating Minio.

**Comment by useahawk** [comment]
Couldn't find documentation on how to implelemt minio.
Any news on this? I think it needs something like `s3ForcePathStyle`?
I get `Inaccessible host: opensign.minio.domain at port undefined.`, but think it should be more like `minio.domain:9000/opensign`?

**Comment by vitorkaviski-ql** [comment]
I haven't found a way to connect my Minio with OpenSign, would anyone know a way to do this?

**Comment by vitorkaviski-ql** [comment]
> I gave up using this application for this reason!

I understand, really, if there's no way, I won't be able to use it either!
