### ISSUE TITLE
Prodcution Docker Containers

### ISSUE THREAD

**Issue by accforgithubtest** [OpenSignLabs/OpenSign#73]
Would be great to have a "production" version published to dockerhub / ghcr / etc. 
This will also allow for a simpler docker compose set up.

**Comment by andrew-opensignlabs** [comment]
@accforgithubtest we will soon have support for docker.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs @andrew-opensignlabs 
Since now our docker compose works well we can publish them to docker hub.
Let me know your thoughts

**Comment by maoo** [comment]
@andrew-opensignlabs @rishabjasrotia  - I'd be happy to help out here

**Comment by andrew-opensignlabs** [comment]
Thanks @maoo There are some major Docker related changes we are working on. We will be publishing those by tomorrow. I would suggest you to wait till tomorrow so that you dont waste time on working on the same thing. Once the changes are published, you can add on to it.

**Comment by lordpayder** [comment]
Hi, is there any news regarding official images published on a public registry dockerhub?

**Comment by ZachHandley** [comment]
Also chiming in to say +1 to production docker, right now it seems like it expects me to have the files there and there's no production docker guide

**Comment by compgeniuses** [comment]
Hi All, Apologies, what is the status of this matter as it is now?

**Comment by Zathiel** [comment]
Hi.

Docker related issue will be followed in https://github.com/OpenSignLabs/OpenSign/issues/795
