### ISSUE TITLE
Change the size of view password button (eye) size on the login page.

### ISSUE THREAD

**Issue by pranav514** [OpenSignLabs/OpenSign#75]
design of the login/signup button in the blog section needs to be improved ,some border radius , hover effect needed to be added

**Comment by pranav514** [comment]
@nxglabs pls assign this issue to me

**Comment by Saurabhyadav0** [comment]
@nxglabs  can to assign to me sir?

**Comment by pranav514** [comment]
@nxglabs I am a beginner ,I am unable to find the login/singup code in the project ,so can you  help me with it

**Comment by nxglabs** [comment]
@pranav514 the blog login button is not a part of the main app. I have changed the issue title to fox the size of view password button on login page. It should be slightly smaller, refer the button size on signup page.

**Comment by pranav514** [comment]
@nxglabs  where is the view password button (eye) I am unable to view it  
![image](https://github.com/OpenSignLabs/OpenSign/assets/76992202/f94992ba-5699-484b-973b-f76de252efa5)
![image](https://github.com/OpenSignLabs/OpenSign/assets/76992202/ea23e362-e7d3-4f2a-a65c-2c35bb73446e)

**Comment by nxglabs** [comment]
You need to visit app.opensignlabs.com
