### ISSUE TITLE
Add "Deploy to Digital Ocean" button

### ISSUE THREAD

**Issue by nxglabs** [OpenSignLabs/OpenSign#8]
We need to create "Deploy to Digital Ocean" button in the README.md file that should ideally setup the entire app on Digital Ocean with once click.

Below are the steps we need to follow -
- Deploy the React frontend app from apps/OpenSign folder of the repo as a component
- Deploy the API from apps/OpenSignServer of the repo as another component
- Setup a MongoDB that will store & retrieve the data via API.
- Setup all Environment variables(some will be auto generated during runtime, some will have fixed default values & users will be asked to enter the values for some others)

CI=false
PUBLIC_URL=https://yourdomain.com/
GENERATE_SOURCEMAP=false
REACT_APP_SEVERURL=https://yourdomain.com/api/app
REACT_APP_APPID=opensignnaxn (you can change this if you want)
APP_ID=opensignnaxn (You can change this if you want)
appName=open_sign_server (you can change this if you want)
MASTER_KEY= Any random key that will be used as masterkey(should be at least 12 character long)
MONGODB_URI = mongodb://root:example@opensigndb/OpenSignDB?authSource=admin
PARSE_MOUNT = /app
SERVER_URL= url where api is deployed (in general it is yourdomain.com/api/app
TZ=Asia/Kolkata (timezone)
DO_SPACE= digital ocean space name
DO_ENDPOINT= digital ocean spaces endpoint
DO_BASEURL = digitial ocean spaces base url
DO_ACCESS_KEY_ID= digital ocean access key id
DO_SECRET_ACCESS_KEY = digital ocean secret access key
DO_REGION = us-west (digital ocean region)
MAILGUN_API_KEY = mailgun.com API key
MAILGUN_DOMAIN = mail.yourdomain.com
MAILGUN_SENDER = postmaster@yourdomain.com
PFX_BASE64 = base64 encoded document signing certificate - pfx or p12)

**Comment by georgioupanayiotis** [comment]
can you assign this to me please @nxglabs

**Comment by nxglabs** [comment]
@all-contributors please add @nxglabs for code
