### ISSUE TITLE
Print button not working on mobile view

### ISSUE THREAD

**Issue by Emm-dev0** [OpenSignLabs/OpenSign#81]
After signing the documents and saving it, the download button works well, but when the print button is clicked, it shows a runtime error.

**Comment by pranav514** [comment]
@Emm-dev0  where were you able to login on the local machine?

**Comment by Emm-dev0** [comment]
I did the testing on a mobile device, logging in was not an issue.

**Comment by andrew-opensignlabs** [comment]
@pranav514 did you try running http://localhost:3000 in chrome incognito window?

**Comment by pranav514** [comment]
@andrew-opensignlabs I tried but still I am unable to login...I also did hard refresh but still it is not woking

**Comment by pranav514** [comment]
@andrew-opensignlabs first I tried to register but an localhost:3000 alert appears

**Comment by rishabjasrotia** [comment]
@nxglabs assign this to me I am willing to work on this issue.

**Comment by andrew-opensignlabs** [comment]
@rishabjasrotia for your information, the print button works perfectly on my Iphone. The issue seems to be only with Android.

**Comment by rishabjasrotia** [comment]
Hello @andrew-opensignlabs 
I investigated on this issue.

The library which we use for printing PDF is facing this issue long time:

1. https://github.com/crabbly/Print.js/issues/677
2. https://github.com/crabbly/Print.js/issues/632

Also this feature does not work in official website demo: https://printjs.crabbly.com/

**Comment by rishabjasrotia** [comment]
Hello @andrew-opensignlabs @nxglabs 

I have raised PR #143 please have a look.

**Comment by rishabjasrotia** [comment]
Hello @nxglabs 
The #143 is merged we can close this issue.
