### ISSUE TITLE
[Bug]: Signature cannot be saved when user name has special characters

### ISSUE THREAD

**Issue by cube-one-gxp-lifescience-partner** [OpenSignLabs/OpenSign#884]
### Issue Description

After uploading a signature it cannot be saved as there is an error message regarding special characters if the user name hasst special characters.

### Expected Behavior

The signature can be uploaded and saved.

### Current Behavior

The signature can be uploaded but not saved.

### Steps to reproduce

1. Have a user account with special characters in its name.
2. Have a signature PNG
3. Upload and save the signature

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Docker Image

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

1.8.1

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@cube-one-gxp-lifescience-partner thanks for reporting this.
Can you share examples of some special characters that are not supported?

**Comment by cube-one-gxp-lifescience-partner** [comment]
Yes, the characters I tested are 'ä' 'ö' 'ü' and 'ß'.

**Comment by andrew-opensignlabs** [comment]
@cube-one-gxp-lifescience-partner We have added support for special characters including the ones mentioned above in OpenSign v2.1.0. Please check & let us know if it works for you.

**Comment by 1024mb** [comment]
> We have added support for special characters including the ones mentioned above in OpenSign v2.1.0. Please check & let us know if it works for you.

It's not working for me, my user name has an "Á".

```
XHRPOST
https://opensign.domain.com/app/files/Áxxxxx_Xxxxx_sign.png
[HTTP/2 400  29ms]

sign upload err Error: Filename contains invalid characters.
```

I'm running version 2.3.3
