### ISSUE TITLE
[Bug]: Documentation lacking a step

### ISSUE THREAD

**Issue by bigbeka** [OpenSignLabs/OpenSign#886]
### Issue Description

`make build` step in the docker installation guide for Linux is missing a step to check if `npm` is installed on the host. If it is not installed, `make build` can't continue to `npm install`.
https://docs.opensignlabs.com/docs/self-host/docker/run-locally

### Expected Behavior

`make build` needs to check if all the dependencies for building are installed.

### Current Behavior

If `npm` is not installed, `make build` fails.

### Steps to reproduce

Run `make build` on a host without `npm` installation.

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Debian Proxmox > LXC Ubuntu 22.04

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.0.0

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@bigbeka documentation has been updated.
