### ISSUE TITLE
Feature Request: Digital signature for US Esign ACT

### ISSUE THREAD

**Issue by jeffsampaul** [OpenSignLabs/OpenSign#900]
### Feature Title

Digital signing

### Feature Description

Hi Open Sign Team,

Are we using the digital signature mechanism like anything below?

There are 2 keys associated with the user(Private and Public key)
Hash value generation: A unique hash value is generated from the document's contents.
Private key encryption: The hash value is encrypted using the signer's private key (or a temporary key).
Digital signature generation: The encrypted hash value becomes the digital signature.

### Importance

Critical

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by nxglabs** [comment]
Yes, we comply with the US esign act.
