### ISSUE TITLE
Admin Panel for self host

### ISSUE THREAD

**Issue by freedy82** [OpenSignLabs/OpenSign#918]
### Feature Title

Is there are have admin panel for self hosting?

### Feature Description

So far seem it was allow free register any account? 
Any control to disable allow register new account or admin panel to control account list? such as edit or delete?

### What type of feature are you requesting?

Other

### Importance

Critical

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@freedy82 In the upcoming release v2.1.0, expected on Monday, Admins will gain the capability to create users and assign roles. This release will also introduce significant changes to the self-hosted version.

**Comment by freedy82** [comment]
Thanks for your answer, btw. when I using self hosting version. I try register a account, and go Profile section. and click "Edit" button it seem throw a JS error and make the Edit function seem not working. I am not sure how to report this issue as the JS was chunked.  in browser console it just display
Uncaught TypeError: W is undefined.

**Comment by freedy82** [comment]
also, are you meaning currently version (2.0.0) have "admins"? just do not have above function? how can I access admin panel or login as admin?

**Comment by andrew-opensignlabs** [comment]
@freedy82 Please upgrade to v2.1.0
Make sure you follow the instructions in the release notes.
