### ISSUE TITLE
[Bug]: API endpoint for selfhost?

### ISSUE THREAD

**Issue by freedy82** [OpenSignLabs/OpenSign#919]
### Issue Description

For example to get document list 
For online is
https://app.opensignlabs.com/api/v1/documentlist/:doctype

I self hosting server config is
http://192.168.31.120:8080/app

I try both below was not working?
http://192.168.31.120:8080/app/documentlist/:doctype
http://192.168.31.120:8080/app/api/documentlist/:doctype
http://192.168.31.120:8080/app/v1/documentlist/:doctype
http://192.168.31.120:8080/app/api/v1/documentlist/:doctype

All return
Array
(
    [error] => unauthorized
)
I already generate token, same code using online seem work fine.

### Expected Behavior

Should work like online version?

### Current Behavior

Seem API was not working?

### Screenshots of the issue(optional)

Just return json with
Array
(
    [error] => unauthorized
)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Windows 11

### What browsers are you seeing the problem on?

Chrome, Firefox

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.0.0

### What environment are you seeing the problem on?

Dev (localhost or vercel)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@freedy82 APIs are not a part of the self-hosted offering.
