### ISSUE TITLE
[Bug]: Cannot log-in to OpenSign account

### ISSUE THREAD

**Issue by Aldy-blip** [OpenSignLabs/OpenSign#940]
### Issue Description

Created yesterday and today 2 documents for e-signing and shared by email through the portal (free account). However, 1 email did not arrive at recipient. Today, tried to log-in to my OpenSign account, however it says invalid userid or password. Tried to reset the password by filling in my email address, but did not receive any emails from OpenSign to reset my password.

My question: is there an issue with OpenSign server/ emails, as none of those are being received by myself (account holder) or my recipients (for e-signing documents)?

### Expected Behavior

I expect that I can normally sign into my account (which was the case in the last few weeks)

### Current Behavior

I cannot sign-in, nor receiving emails from OpenSign to reset my password. Also my recipients did not receive emails from OpenSign for e-signing documents

### Steps to reproduce

homepage of portal to log-in. There is where it already fails.

### Screenshots of the issue(optional)

None

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Windows 10

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

cannot see on homepage OpenSign

### What environment are you seeing the problem on?

Production (app.opensignlabs.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by nxglabs** [comment]
There is no issue with the system. Please share your email id that you used
to create the account on ***@***.***

**Comment by Aldy-blip** [comment]
Here it is:   
  
***@***.***
  

  
Thank you!
  
  
  
  
  
  
  

  
  
>

**Comment by Aldy-blip** [comment]
Are you able to see what the issue is with my account?
  
  
  
  
  
  
  

  
  
>

**Comment by andrew-opensignlabs** [comment]
@Aldy-blip Please email us on hello@opensignlabs.com from the email id that you registered with.
