### ISSUE TITLE
[Bug]: Credentials to login on local install 

### ISSUE THREAD

**Issue by viniciusbrun-dev** [OpenSignLabs/OpenSign#973]
### Issue Description

Can't find credentials to login on local install

This seems to be the same issue as "Credentials #218". However, in that case there was a register button and the issue was closed. Now, on v2.0.0 there is no register button. 

### Expected Behavior

Know the credentials for login or be able to create new user. 

### Current Behavior

Don't know if there is a default user ot how to create one.

### Steps to reproduce

Local install on ubuntu 22.04.

### Screenshots of the issue(optional)

![image](https://github.com/user-attachments/assets/40f5070f-4812-4958-88c2-94f6c37efbf7)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Ubuntu 22.04

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.0.0

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by andrew-opensignlabs** [comment]
@viniciusbrun-dev upgrade to v2.1.0
Make sure that you go through the upgrade instructions in the release notes before you upgrade.

**Comment by viniciusbrun-dev** [comment]
Okay, thank you very much!
